FROM r-base

RUN 
RUN R -e "install.packages('BiocManager')"
RUN R -e "BiocManager::install('Biobase')"
RUN R -e "BiocManager::install('EBImage')"
RUN R -e "install.packages('curl')"

COPY . /usr/local/src/myscripts
WORKDIR /usr/local/src/myscripts

# RUN "R -e 'install.packages("BiocManager")' &&
#     R -e 'BiocManager::install("Biobase")' && 
#     R -e 'BiocManager::install("EBImage")' && 
#     R -e  'install.packages("curl")'"

CMD ["Rscript", "Reanalysis.R"]