name: run an R script
on: 
  push:
    branches:
      - "main"
      - "feat/adding-github-actions"
  #schedule:
  #  - cron: '31 13 * * *'
  workflow_dispatch:

jobs:
  run_r_script:
    defaults:
      run:
        shell: bash
    name: 'Run r script'
    runs-on: ubuntu-20.04
    environment: RUN
    env:
      #OBJ_STORE_BUCKET: ${{ secrets.OBJ_STORE_BUCKET }}
      #OBJ_STORE_SECRET: ${{ secrets.OBJ_STORE_SECRET }}
      #OBJ_STORE_USER: ${{ secrets.OBJ_STORE_USER }}
      #OBJ_STORE_HOST: ${{ secrets.OBJ_STORE_HOST }}
      #WGRIB_UTILITY: /usr/local/bin/wgrib2
      TEST: test

    steps:
    - uses: actions/checkout@v3
      id: checkout
      with:
       fetch-depth: 0

    - name: Setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: 4.2.1

    # - name: install r dependencies
    #   uses: r-lib/actions/setup-r-dependencies@v2
    #   with:
    #     cache-version: 2
    #     needs: |
    #       EBImage
    #       curl

    - id: install-r-dependencies
      name: Install r dependencies
      run: |
        /usr/local/bin/Rscript InstallPackages.R

    - id: run-the-r-script
      name: Runs the r script
      shell: bash
      run: |
        /usr/local/bin/Rscript Reanalysis.R
        